name: Deploy Frontend to App Engine

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'package.json'
      - 'package-lock.json'
      - 'vite.config.ts'
      - 'app.yaml'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build frontend
        run: npx vite build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: gerenciai-476500

      - name: Deploy to App Engine
        run: gcloud app deploy --quiet --project=gerenciai-476500

      - name: Deployment complete
        run: |
          echo "✅ Frontend deployed successfully!"
          echo "🌐 URL: https://arenai.com.br"
          echo "📱 App Engine: https://gerenciai-476500.ue.r.appspot.com"
